name: QDU Info Submit

on:
  schedule:
    - cron: "0 */4 * * *"
  push:
    branches:
    - main
  watch:
    types: [started]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: run script
      env:
        PHONE: ${{ secrets.PHONE }}
        PASSWORD: ${{ secrets.PASSWORD }}
        KEYWORD: ${{ secrets.KEYWORD }}
        FIELDS: ${{ secrets.FIELDS }}
      run: |
        python tiwen.py